// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	io "io"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HTTPPoster is an autogenerated mock type for the HTTPPoster type
type HTTPPoster struct {
	mock.Mock
}

// Post provides a mock function with given fields: _a0, _a1, _a2
func (_m *HTTPPoster) Post(_a0 string, _a1 string, _a2 io.Reader) (*http.Response, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) *http.Response); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
