name: Release

on:
  pull_request:
    branches:
      - development
      #- master
    types: [closed]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - uses: actions/checkout@v2

    - name: Build
      run: go build -o . ./cmd/faas/...

    - name: Upload binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./faas
        tag: ${{ github.sha }}
